### PyTorch

It is an open source machine learning libray which is used for application such as computer vision and NLP

**Features**
- Extensive neural network building blocks
- Built-in back propagation with autograd
- A simple, intuitive and stable API

In [2]:
# Installation 
!pip install torch

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 906.4/906.4 MB 620.1 kB/s eta 0:00:0000:0100:10
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 1.3 MB/s eta 0:00:0000:0100:06
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 1.6 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 2.0 MB/s eta 0:00:0000:0100:02
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.7/188.7 MB 1.7 MB/s eta 0:00:0000:0100:03
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 2.0 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 1.9 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 2.4 MB/s eta 0:00:0000:0100:01
  Using cached jinja2-3.1.4-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.5/209.5 MB 1.6 MB/s eta 0:00:0000:0100:03
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 1.2 MB/s eta 0:00:0000:0100:03
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

In [3]:
import torch

In [4]:
torch.rand(2,2)

tensor([[0.2706, 0.9718],
        [0.0686, 0.3112]])

In [ ]:
x = torch.empty(4) # 1D tensor
x

tensor([ 8.5591e-21,  4.5074e-41, -4.4257e-31,  3.1306e-41])

In [ ]:
y = torch.empty(2,3) # 2D tensor
y

tensor([[1.8394e+25, 6.1963e-04, 4.1185e-11],
        [7.4712e+22, 1.8609e+34, 1.0302e+21]])

In [ ]:
torch.empty(2,2,3) # 3D tensor

tensor([[[-5.2550e-32,  3.1306e-41, -7.5088e+27],
         [ 4.5073e-41,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]])

In [9]:
torch.empty(3,2,2,4)

tensor([[[[-5.3915e-31,  3.1306e-41,  8.5592e-21,  4.5074e-41],
          [ 0.0000e+00,  0.0000e+00,  3.6013e-43,  0.0000e+00]],

         [[ 8.5590e-21,  4.5074e-41,  8.5590e-21,  4.5074e-41],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]],


        [[[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

         [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]],


        [[[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

         [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]]])

In [10]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [14]:
x = torch.ones(2,2)
x

tensor([[1., 1.],
        [1., 1.]])

In [15]:
x.size()

torch.Size([2, 2])

In [16]:
x.ndim

2

In [17]:
x = torch.ones(3,3,dtype=torch.int)
x

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [18]:
torch.tensor([4.2,3.1,5,2])

tensor([4.2000, 3.1000, 5.0000, 2.0000])

In [21]:
torch.manual_seed(42)
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])
tensor([[0.3904, 0.6009],
        [0.2566, 0.7936]])


In [22]:
z = x + y
z

tensor([[1.2727, 1.5159],
        [0.6394, 1.7529]])

In [23]:
torch.add(x,y)

tensor([[1.2727, 1.5159],
        [0.6394, 1.7529]])

In [24]:
z = x - y
z

tensor([[0.4918, 0.3141],
        [0.1263, 0.1657]])

In [25]:
torch.sub(x,y)

tensor([[0.4918, 0.3141],
        [0.1263, 0.1657]])

In [27]:
print(torch.mul(x,y))
print(torch.div(x,y))

tensor([[0.3445, 0.5498],
        [0.0982, 0.7613]])
tensor([[2.2596, 1.5227],
        [1.4922, 1.2087]])


In [29]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

tensor([[0.8694, 0.5677],
        [0.7411, 0.4294]])
tensor([[0.8854, 0.5739],
        [0.2666, 0.6274]])


In [ ]:
y.add_(x) # inplace addition operation 

tensor([[1.7548, 1.1416],
        [1.0077, 1.0569]])

In [32]:
z = x + y
z

tensor([[2.6243, 1.7093],
        [1.7488, 1.4863]])

In [34]:
x = torch.rand(5,3)
x

tensor([[0.8090, 0.5779, 0.9040],
        [0.5547, 0.3423, 0.6343],
        [0.3644, 0.7104, 0.9464],
        [0.7890, 0.2814, 0.7886],
        [0.5895, 0.7539, 0.1952]])

In [35]:
x[:,0]

tensor([0.8090, 0.5547, 0.3644, 0.7890, 0.5895])

In [36]:
x[:,1]

tensor([0.5779, 0.3423, 0.7104, 0.2814, 0.7539])

In [38]:
x = torch.rand(1)
x

tensor([0.3068])

In [39]:
x.item()

0.30681973695755005

In [42]:
x = torch.rand(4,4)
x

tensor([[0.2018, 0.2018, 0.9497, 0.6666],
        [0.9811, 0.0874, 0.0041, 0.1088],
        [0.1637, 0.7025, 0.6790, 0.9155],
        [0.2418, 0.1591, 0.7653, 0.2979]])

In [43]:
x.shape

torch.Size([4, 4])

In [47]:
x.view(16)

tensor([0.2018, 0.2018, 0.9497, 0.6666, 0.9811, 0.0874, 0.0041, 0.1088, 0.1637,
        0.7025, 0.6790, 0.9155, 0.2418, 0.1591, 0.7653, 0.2979])

In [48]:
x.view(2,2,4)

tensor([[[0.2018, 0.2018, 0.9497, 0.6666],
         [0.9811, 0.0874, 0.0041, 0.1088]],

        [[0.1637, 0.7025, 0.6790, 0.9155],
         [0.2418, 0.1591, 0.7653, 0.2979]]])

In [53]:
# converting tensor into a numpy array
a = torch.ones(6)
print(a)
print(type(a))

tensor([1., 1., 1., 1., 1., 1.])
<class 'torch.Tensor'>


In [55]:
import numpy as np

b = a.numpy()
print(b)
print(type(b))

[1. 1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [56]:
a.add_(3)

tensor([4., 4., 4., 4., 4., 4.])

In [57]:
b

array([4., 4., 4., 4., 4., 4.], dtype=float32)

In [58]:
# Convert Numpy array to a tensor

a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [59]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [60]:
a+=2
a

array([3., 3., 3., 3., 3.])

In [61]:
b

tensor([3., 3., 3., 3., 3.], dtype=torch.float64)

In [63]:
# Backpropagation in PyTorch
x = torch.tensor(4., requires_grad=True)
x

tensor(4., requires_grad=True)

In [64]:
y = x ** 3
y

tensor(64., grad_fn=<PowBackward0>)

In [66]:
# dy/dx = 3x**2

y.backward()

In [69]:
print(x.grad)

tensor(48.)


In [71]:
l1 = [[2.,3.,5.],[6.,9.,11.],[13.,17.,18.]]
x = torch.tensor(l1, requires_grad=True)
x

tensor([[ 2.,  3.,  5.],
        [ 6.,  9., 11.],
        [13., 17., 18.]], requires_grad=True)

In [74]:
y  = x ** 3 + x ** 2
y

tensor([[  12.,   36.,  150.],
        [ 252.,  810., 1452.],
        [2366., 5202., 6156.]], grad_fn=<AddBackward0>)

In [77]:
# dy/dx = 3x**2 + 2x
z = y.sum()
z

tensor(16436., grad_fn=<SumBackward0>)

In [78]:
z.backward()

In [79]:
x.grad

tensor([[  16.,   33.,   85.],
        [ 120.,  261.,  385.],
        [ 533.,  901., 1008.]])