### Numpy Arrays

In [ ]:
# 1d array - Vectors and 2d arrays - matrices

In [7]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [1]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [8]:
arr

array([1, 2, 3])

In [9]:
my_mat = [[1,2,3],[4,5,6],[6,7,8]]
my_mat

[[1, 2, 3], [4, 5, 6], [6, 7, 8]]

In [10]:
mat = np.array(my_mat)

In [11]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [13]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [23]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [24]:
np.zeros(3)

array([0., 0., 0.])

In [25]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.ones(4)

array([1., 1., 1., 1.])

In [27]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
np.ones((2,2),dtype=int)

array([[1, 1],
       [1, 1]])

In [30]:
np.linspace(0,5,10) # 0 to 5 - 10 equal points 

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [33]:
np.linspace(0,5,50)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [38]:
np.eye(4) # identity matrics

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [49]:
np.random.rand(5) # generate random values from 0 to 1

array([0.57300295, 0.26010212, 0.16840116, 0.41610648, 0.92030386])

In [54]:
np.random.randn(4,4) # Return a sample (or samples) from the "standard normal" distribution.

array([[ 0.46203411,  0.8403856 , -0.59894102,  0.15683789],
       [ 1.62558659, -0.55374123, -0.1043    , -0.95886912],
       [-0.80305615, -1.18931664, -0.20949023, -1.15762761],
       [ 1.47260947, -1.33289077,  0.38838731,  1.97790375]])

In [56]:
np.random.randint(1,100) # gives you random integer b/w 1 to 100

47

In [ ]:
np.random.randint(1,100,10) # gives 10 random integers

array([33, 46, 52, 20, 84, 15, 70, 40, 11, 93])

In [58]:
ranarr = np.random.randint(0,50,10)

In [59]:
ranarr

array([35, 18, 23,  6, 16, 37, 16,  7, 37, 28])

In [ ]:
ranarr.reshape(2,5) # rows, columns = rows*columns values

array([[35, 18, 23,  6, 16],
       [37, 16,  7, 37, 28]])

In [65]:
ranarr.min()

np.int64(6)

In [66]:
ranarr.max()

np.int64(37)

In [68]:
ranarr.argmax() # location of maximum value

np.int64(5)

In [69]:
ranarr.argmin()

np.int64(3)

In [75]:
ranarr1 = ranarr.reshape(5,2)
ranarr1

array([[35, 18],
       [23,  6],
       [16, 37],
       [16,  7],
       [37, 28]])

In [76]:
ranarr1.shape

(5, 2)

In [77]:
ranarr.dtype

dtype('int64')

In [78]:
from numpy.random import randint

In [79]:
randint(0,10,2)

array([3, 6])

### Numpy Indexing and Selection

In [80]:
import numpy as np

In [81]:
arr = np.arange(0,11)

In [82]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
arr[8]

np.int64(8)

In [84]:
arr[1:5]

array([1, 2, 3, 4])

In [89]:
arr[0:-2]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [91]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [92]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [93]:
arr[0:5] = 100

In [94]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [95]:
arr = np.arange(0,11)

In [96]:
slice_of_arr = arr[0:6]

In [97]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [99]:
slice_of_arr[:] = 99

In [100]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [101]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [102]:
arr_copy = arr.copy()

In [103]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [104]:
arr_copy[:7] = 100

In [105]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100,   7,   8,   9,  10])

In [106]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [107]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [108]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [111]:
arr_2d[0,0] # row and column to get specific value from matrix

np.int64(5)

In [113]:
arr_2d[0] # 0th row

array([ 5, 10, 15])

In [117]:
arr_2d[:,0]

array([ 5, 20, 35])

In [120]:
arr_2d[1][2]

np.int64(30)

In [119]:
arr_2d[1,2]

np.int64(30)

In [122]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [125]:
arr_2d[:3,:2]

array([[ 5, 10],
       [20, 25],
       [35, 40]])

In [126]:
arr = np.arange(1,11)

In [127]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [128]:
bool_arr = arr > 5

In [129]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [130]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [131]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [132]:
arr[arr<3]

array([1, 2])

In [133]:
arr_2d = np.arange(50).reshape(5,10)

In [134]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [135]:
arr_2d[1,3:5]

array([13, 14])

In [136]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

### Numpy Operations

- Array with Array
- Array with Scalars
- Universal Array Functions

In [137]:
import numpy as np

In [138]:
arr = np.arange(0,11)

In [139]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [141]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [142]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [143]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [146]:
# Scalar operations : scalar means single number, what numpy does broadcast that number on every element in the array so the operations occurs on element by element basis.

In [147]:
arr - 10

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [148]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [151]:
arr / arr

/tmp/ipykernel_75376/3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [153]:
1 / arr # inf - infinity ( 1 / 0)

/tmp/ipykernel_75376/1261094336.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr # inf - infinity ( 1 / 0)


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [154]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [156]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [157]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [158]:
np.max(arr)

np.int64(10)

In [159]:
np.min(arr)

np.int64(0)

In [160]:
np.sum(arr)

np.int64(55)

In [161]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [ ]:
np.log(arr) 

/tmp/ipykernel_75376/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])